import 'package:floor/floor.dart';


@Entity(primaryKeys: ['date'])
class SleepData{
  //id will be the primary key of the table. Moreover, it will be autogenerated.
  //id is nullable since it is autogenerated.
  
  final String date; 
  final double duration;
  final int? efficiency;
  final int? deep;
  final int? rem;
  final int? wake;
  final double? quiz;

  //Default constructor
  SleepData(this.date, this.duration, this.efficiency, this.deep,this.rem,this.wake, this.quiz);
  
}//SleepData